name: network_to_file_image
description: Opens an image from a file, otherwise downloads from the internet and saves to the file
version: 0.0.2
author: Marcelo Glasberg <marcglasberg@gmail.com>
homepage: https://github.com/marcglasberg/network_to_file_image

environment:
  sdk: ">=2.0.0 <5.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

